.TH "libft/src Directory Reference" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_atoi\&.c\fP"
.br
.ti -1c
.RI "file \fBft_atoi_base\&.c\fP"
.br
.ti -1c
.RI "file \fBft_bzero\&.c\fP"
.br
.ti -1c
.RI "file \fBft_getndigits\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isalnum\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isalpha\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isascii\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isdigit\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isprint\&.c\fP"
.br
.ti -1c
.RI "file \fBft_isupper\&.c\fP"
.br
.ti -1c
.RI "file \fBft_itoa\&.c\fP"
.br
.ti -1c
.RI "file \fBft_lstadd_funcs\&.c\fP"
.br
.ti -1c
.RI "file \fBft_lstmanage_funcs\&.c\fP"
.br
.ti -1c
.RI "file \fBft_mat\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memalloc\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memccpy\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memcmp\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memdel\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memmove\&.c\fP"
.br
.ti -1c
.RI "file \fBft_memset\&.c\fP"
.br
.ti -1c
.RI "file \fBft_pmem\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putchar\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putchar_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putendl\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putendl_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putnbr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putnbr_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putstr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_putstr_fd\&.c\fP"
.br
.ti -1c
.RI "file \fBft_realloc\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strcat\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strcchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strclchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strclr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strcmp\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strdel\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strdup\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strequ\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strinv\&.c\fP"
.br
.ti -1c
.RI "file \fBft_striter\&.c\fP"
.br
.ti -1c
.RI "file \fBft_striteri\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strjoin\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strlcat\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strlen\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strmap\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strmapi\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strncat\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strncmp\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strncpy\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strnequ\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strnew\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strnstr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strrchr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strsplit\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strstr\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strsub\&.c\fP"
.br
.ti -1c
.RI "file \fBft_strtrim\&.c\fP"
.br
.ti -1c
.RI "file \fBft_swap\&.c\fP"
.br
.ti -1c
.RI "file \fBft_tabmax\&.c\fP"
.br
.ti -1c
.RI "file \fBft_tolower\&.c\fP"
.br
.ti -1c
.RI "file \fBft_toupper\&.c\fP"
.br
.ti -1c
.RI "file \fBget_next_line\&.c\fP"
.br
.in -1c
