.TH "src/builtins_env.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins_env.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static char ** \fBfill_nenv\fP (char opts, char ***av)"
.br
.ti -1c
.RI "static int \fBgeto\fP (char ***av)"
.br
.ti -1c
.RI "int \fBbi_env\fP (char **av)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int bi_env (char ** av)"

.SS "static char** fill_nenv (char opts, char *** av)\fC [inline]\fP, \fC [static]\fP"

.SS "static int geto (char *** av)\fC [inline]\fP, \fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
