.TH "src/builtins_env.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins_env.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBbi_env\fP (char **av)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int bi_env (char ** av)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
