.TH "src/builtins_cd.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/builtins_cd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static char * \fBset_curpath\fP (char **av)"
.br
.ti -1c
.RI "static int \fBcanon_form\fP (char **path, char *ocurdir)"
.br
.ti -1c
.RI "int \fBbi_cd\fP (char **av)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int bi_cd (char ** av)"

.SS "static int canon_form (char ** path, char * ocurdir)\fC [inline]\fP, \fC [static]\fP"

.SS "static char* set_curpath (char ** av)\fC [inline]\fP, \fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
