.TH "src/command.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/command.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <minishell\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBforkexec\fP (char *cmd, char **av, char **env)"
.br
.ti -1c
.RI "int \fBin_builtins\fP (char **av)"
.br
.ti -1c
.RI "int \fBcommand\fP (char *line, char **env, int bi)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int command (char * line, char ** env, int bi)"

.SS "int forkexec (char * cmd, char ** av, char ** env)"

.SS "int in_builtins (char ** av)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
