.TH "libft/src/ft_itoa.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_itoa.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fBget_ndigits\fP (int num)"
.br
.ti -1c
.RI "char * \fBft_itoa\fP (int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* ft_itoa (int n)"

.SS "static int get_ndigits (int num)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
