.TH "libft/src/ft_lstadd_funcs.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_lstadd_funcs.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_lstadd\fP (\fBt_list\fP **alst, \fBt_list\fP *new)"
.br
.ti -1c
.RI "int \fBft_lstinsert_list\fP (\fBt_list\fP *fflist, \fBt_list\fP *ffnew, int(*f)(\fBt_list\fP *, \fBt_list\fP *))"
.br
.ti -1c
.RI "\fBt_list\fP * \fBft_lstinsert\fP (\fBt_list\fP **fflist, \fBt_list\fP *new, int(*f)(\fBt_list\fP *, \fBt_list\fP *))"
.br
.ti -1c
.RI "void \fBft_lstappend\fP (\fBt_list\fP *alst, \fBt_list\fP *new)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_lstadd (\fBt_list\fP ** alst, \fBt_list\fP * new)"

.SS "void ft_lstappend (\fBt_list\fP * alst, \fBt_list\fP * new)"

.SS "\fBt_list\fP* ft_lstinsert (\fBt_list\fP ** fflist, \fBt_list\fP * new, int(*)(\fBt_list\fP *, \fBt_list\fP *) f)"

.SS "int ft_lstinsert_list (\fBt_list\fP * fflist, \fBt_list\fP * ffnew, int(*)(\fBt_list\fP *, \fBt_list\fP *) f)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
