.TH "libft/src/ft_mat.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_mat.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_pow\fP (int n, int p)"
.br
.ti -1c
.RI "unsigned int \fBft_abs\fP (signed int n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "unsigned int ft_abs (signed int n)"

.SS "int ft_pow (int n, int p)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
