.TH "libft/src/ft_memalloc.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_memalloc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_memalloc\fP (size_t size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* ft_memalloc (size_t size)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
