.TH "libft/src/ft_memdel.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_memdel.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_memdel\fP (void **ap)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_memdel (void ** ap)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
