.TH "libft/src/ft_pmem.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_pmem.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fBisascii\fP (char c)"
.br
.ti -1c
.RI "void \fBft_puthex\fP (unsigned char num)"
.br
.ti -1c
.RI "char * \fBprint_line_ascii\fP (char *addr, int b)"
.br
.ti -1c
.RI "void \fBft_pmem\fP (const void *addr, size_t t)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_pmem (const void * addr, size_t t)"

.SS "void ft_puthex (unsigned char num)"

.SS "static int isascii (char c)\fC [inline]\fP, \fC [static]\fP"

.SS "char* print_line_ascii (char * addr, int b)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
