.TH "libft/src/ft_putchar_fd.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_putchar_fd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_putchar_fd\fP (char c, int fd)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_putchar_fd (char c, int fd)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
