.TH "libft/src/ft_putstr.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_putstr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_putstr\fP (char const *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ft_putstr (char const * s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
