.TH "libft/src/ft_realloc.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_realloc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBft_realloc\fP (void **src, size_t src_size, size_t final_size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* ft_realloc (void ** src, size_t src_size, size_t final_size)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
