.TH "libft/src/ft_strsub.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_strsub.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strsub\fP (char const *s, unsigned int start, size_t len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* ft_strsub (char const * s, unsigned int start, size_t len)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
