.TH "libft/src/ft_strncmp.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_strncmp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_strncmp\fP (char const *s1, char const *s2, size_t n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_strncmp (char const * s1, char const * s2, size_t n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
