.TH "libft/src/ft_strchr.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_strchr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strchr\fP (char const *s, int c)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* ft_strchr (char const * s, int c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
