.TH "libft/src/ft_strinv.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_strinv.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strinv\fP (char *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* ft_strinv (char * s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
