.TH "libft/src/ft_strlen.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_strlen.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBft_strlen\fP (const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t ft_strlen (const char * str)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
