.TH "libft/src/ft_strcpy.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_strcpy.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strcpy\fP (char *dest, char const *src)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* ft_strcpy (char * dest, char const * src)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
