.TH "libft/src/ft_strcmp.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_strcmp.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBft_strcmp\fP (char *s1, char *s2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ft_strcmp (char * s1, char * s2)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
