.TH "libft/src/ft_strstr.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libft/src/ft_strstr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBft_strstr\fP (char const *s1, char const *s2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* ft_strstr (char const * s1, char const * s2)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
