.TH "src/init.c" 3 "Thu Jul 7 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/init.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBparse_env_conf\fP (char *conffile)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int parse_env_conf (char * conffile)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
