.TH "src/prompt.c" 3 "Wed Jul 6 2016" "minishell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/prompt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'minishell\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsp_prompt\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void sp_prompt (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for minishell from the source code\&.
